#!/usr/bin/env bash
# This script configures Nginx to redirection

apt-get update
apt-get install -y nginx

# Create a backup
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

SERVER=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ http://tajba.tech permanent;
	}
}"

bash -c "echo -e '$SERVER' > /etc/nginx/sites-enabled/default"

service nginx restart
