#!/usr/bin/env bash
#100

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command" && terminator' SIGTERM

terminator()
{
	rm /var/run/myscript.pid
	exit
}
trap terminator SIGQUIT
echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2

done
