#!/usr/bin/env bash
# Script prints "Best School" 10 times when it is 4 says badluck 8 badluck 
i=0
while ((i < 10))
do
	((i++))
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
