#!/usr/bin/env bash
#Change hosts file
cp ~/etc/hosts ~/etc/hosts.new
echo "127.0.0.2         localhost" > ~/etc/hosts.new
echo "8.8.8.8           facebook.com" >> ~/etc/hosts.new
cp -f ~/hosts.new /etc/hosts