#!/usr/bin/env bash
# write a Bash script that accepts one argument
# the script should run the whoami command under the user passed as an argument

# Check arguments
if [ $# -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

# Run 
sudo -u "$1" whoami
