#!/usr/bin/env bash
# Script that make
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080

# Install nginx
if ! command -v nginx &>/dev/null; then
    apt-get update
    apt-get install -y nginx
fi

# Stop nginx if it's already running
systemctl stop nginx

# Configure nginx to run as nginx user and listen on port 8080
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
# Start nginx
sudo -u nginx service nginx start
